# The version of the docker-compose.

version: "3.8"

# Telling docker-compose to build the client and server images and run them in containers.

services:
  client:
    build: ./client
    container_name: clientapp_c
    ports:
      - "5000:3000"
    stdin_open: true
    tty: true

  # server services
  server:
    build: ./server
    container_name: serverapp_c
    ports:
      - 3000:3000
    volumes:
      - .:/server
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      NAME: My Name
    depends_on:
      - mongo_db

  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_db: {}
